services:
  go-service:
    build: .
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/tmp  # Ensure the tmp directory is writable inside the container
    ports:
      - "3000:3000"  # Map the host port 3000 to the container port 3000
    environment:
      - AIR_ENV=${AIR_ENV}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres:13  # Use PostgreSQL version 13 image
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data using a named volume
    ports:
      - "0.0.0.0:5432:5432"  # Expose PostgreSQL on all network interfaces

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: